version: '3.8'

services:
  # Сервис для PostgreSQL
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432" 

  # Сервис для Next.js и Prisma
  fronted:
    container_name: frontend
    image: frontend
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment: 
      DATABASE_URL: ${DATABASE_URL}
      DIRECT_URL: ${DIRECT_URL}
      AUTH_SECRET: ${AUTH_SECRET}
      GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
      GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      RESEND_API_KEY: ${RESEND_API_KEY}
      NEXT_PUBLIC_APP_URL: ${NEXT_PUBLIC_APP_URL}
    depends_on:
      - postgres
    volumes:
      - .:/usr/app
    restart: always
    develop:
      watch:
        - action: rebuild
        - path: .


  